# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

days_in_country_internal <- function(date_crossing, is_arrival, n_crossing_person, date_obs_end, dur_test) {
    .Call('_rbc_days_in_country_internal', PACKAGE = 'rbc', date_crossing, is_arrival, n_crossing_person, date_obs_end, dur_test)
}

is_long_term_mig_internal <- function(is_arrival, res_status_before, res_status_after, days_in_country, days_obs, dur_test, dur_threshold, n_crossing_person) {
    .Call('_rbc_is_long_term_mig_internal', PACKAGE = 'rbc', is_arrival, res_status_before, res_status_after, days_in_country, days_obs, dur_test, dur_threshold, n_crossing_person)
}

person_id_internal <- function(personId, personId_is_na, match1, match2, first_id) {
    invisible(.Call('_rbc_person_id_internal', PACKAGE = 'rbc', personId, personId_is_na, match1, match2, first_id))
}

res_status_after_internal <- function(res_status_initial, is_arrival, days_in_country, days_obs, n_crossing_person, dur_test, dur_threshold) {
    .Call('_rbc_res_status_after_internal', PACKAGE = 'rbc', res_status_initial, is_arrival, days_in_country, days_obs, n_crossing_person, dur_test, dur_threshold)
}

